// Code generated by protoc-gen-go.
// source: bidfeed_msg.proto
// DO NOT EDIT!

/*
Package websidx_interface is a generated protocol buffer package.

It is generated from these files:
	bidfeed_msg.proto
	websidx_msg.proto

It has these top-level messages:
	AdBidFeedContentOps
	KeyValue
	AdBidFeedOpcInfo
	AdBidFeedNativeOpcInfo
	AdBidFeedDetailInfo
	DocumentMsg
*/
package websidx_interface

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// //////// message for feed(ad_type=8) begin //////////
type AdBidFeedContentOps struct {
	Type             *uint32              `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	AdfeedInfo       *AdBidFeedDetailInfo `protobuf:"bytes,2,req,name=adfeed_info,json=adfeedInfo" json:"adfeed_info,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *AdBidFeedContentOps) Reset()                    { *m = AdBidFeedContentOps{} }
func (m *AdBidFeedContentOps) String() string            { return proto.CompactTextString(m) }
func (*AdBidFeedContentOps) ProtoMessage()               {}
func (*AdBidFeedContentOps) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AdBidFeedContentOps) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *AdBidFeedContentOps) GetAdfeedInfo() *AdBidFeedDetailInfo {
	if m != nil {
		return m.AdfeedInfo
	}
	return nil
}

type KeyValue struct {
	Key              *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            []string `protobuf:"bytes,2,rep,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *KeyValue) Reset()                    { *m = KeyValue{} }
func (m *KeyValue) String() string            { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()               {}
func (*KeyValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *KeyValue) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type AdBidFeedOpcInfo struct {
	Age              []uint32    `protobuf:"varint,1,rep,name=age" json:"age,omitempty"`
	Gender           []uint32    `protobuf:"varint,2,rep,name=gender" json:"gender,omitempty"`
	Location         []uint32    `protobuf:"varint,3,rep,name=location" json:"location,omitempty"`
	Interests        []uint32    `protobuf:"varint,4,rep,name=interests" json:"interests,omitempty"`
	Bidwords         []string    `protobuf:"bytes,5,rep,name=bidwords" json:"bidwords,omitempty"`
	Type             *string     `protobuf:"bytes,6,req,name=type" json:"type,omitempty"`
	CustList         []uint64    `protobuf:"varint,7,rep,name=cust_list,json=custList" json:"cust_list,omitempty"`
	RoyaltyPrice     *float64    `protobuf:"fixed64,8,opt,name=royalty_price,json=royaltyPrice" json:"royalty_price,omitempty"`
	Reserved         []*KeyValue `protobuf:"bytes,9,rep,name=reserved" json:"reserved,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *AdBidFeedOpcInfo) Reset()                    { *m = AdBidFeedOpcInfo{} }
func (m *AdBidFeedOpcInfo) String() string            { return proto.CompactTextString(m) }
func (*AdBidFeedOpcInfo) ProtoMessage()               {}
func (*AdBidFeedOpcInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AdBidFeedOpcInfo) GetAge() []uint32 {
	if m != nil {
		return m.Age
	}
	return nil
}

func (m *AdBidFeedOpcInfo) GetGender() []uint32 {
	if m != nil {
		return m.Gender
	}
	return nil
}

func (m *AdBidFeedOpcInfo) GetLocation() []uint32 {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *AdBidFeedOpcInfo) GetInterests() []uint32 {
	if m != nil {
		return m.Interests
	}
	return nil
}

func (m *AdBidFeedOpcInfo) GetBidwords() []string {
	if m != nil {
		return m.Bidwords
	}
	return nil
}

func (m *AdBidFeedOpcInfo) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *AdBidFeedOpcInfo) GetCustList() []uint64 {
	if m != nil {
		return m.CustList
	}
	return nil
}

func (m *AdBidFeedOpcInfo) GetRoyaltyPrice() float64 {
	if m != nil && m.RoyaltyPrice != nil {
		return *m.RoyaltyPrice
	}
	return 0
}

func (m *AdBidFeedOpcInfo) GetReserved() []*KeyValue {
	if m != nil {
		return m.Reserved
	}
	return nil
}

type AdBidFeedNativeOpcInfo struct {
	Enable           *uint32  `protobuf:"varint,1,opt,name=enable" json:"enable,omitempty"`
	Age              []uint32 `protobuf:"varint,2,rep,name=age" json:"age,omitempty"`
	Gender           []uint32 `protobuf:"varint,3,rep,name=gender" json:"gender,omitempty"`
	Location         []uint32 `protobuf:"varint,4,rep,name=location" json:"location,omitempty"`
	Device           []uint32 `protobuf:"varint,5,rep,name=device" json:"device,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *AdBidFeedNativeOpcInfo) Reset()                    { *m = AdBidFeedNativeOpcInfo{} }
func (m *AdBidFeedNativeOpcInfo) String() string            { return proto.CompactTextString(m) }
func (*AdBidFeedNativeOpcInfo) ProtoMessage()               {}
func (*AdBidFeedNativeOpcInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AdBidFeedNativeOpcInfo) GetEnable() uint32 {
	if m != nil && m.Enable != nil {
		return *m.Enable
	}
	return 0
}

func (m *AdBidFeedNativeOpcInfo) GetAge() []uint32 {
	if m != nil {
		return m.Age
	}
	return nil
}

func (m *AdBidFeedNativeOpcInfo) GetGender() []uint32 {
	if m != nil {
		return m.Gender
	}
	return nil
}

func (m *AdBidFeedNativeOpcInfo) GetLocation() []uint32 {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *AdBidFeedNativeOpcInfo) GetDevice() []uint32 {
	if m != nil {
		return m.Device
	}
	return nil
}

type AdBidFeedDetailInfo struct {
	AdId             *uint32                 `protobuf:"varint,1,req,name=ad_id,json=adId" json:"ad_id,omitempty"`
	Status           *int32                  `protobuf:"varint,2,req,name=status" json:"status,omitempty"`
	FeedId           *uint64                 `protobuf:"varint,3,opt,name=feed_id,json=feedId" json:"feed_id,omitempty"`
	CustId           *uint64                 `protobuf:"varint,4,opt,name=cust_id,json=custId" json:"cust_id,omitempty"`
	FeedPostTime     *string                 `protobuf:"bytes,5,opt,name=feed_post_time,json=feedPostTime" json:"feed_post_time,omitempty"`
	Psid             *string                 `protobuf:"bytes,6,opt,name=psid" json:"psid,omitempty"`
	AdType           *int32                  `protobuf:"varint,7,opt,name=ad_type,json=adType" json:"ad_type,omitempty"`
	Impression       *uint32                 `protobuf:"varint,8,opt,name=impression" json:"impression,omitempty"`
	Updatetime       *string                 `protobuf:"bytes,9,opt,name=updatetime" json:"updatetime,omitempty"`
	Version          *int32                  `protobuf:"varint,10,opt,name=version" json:"version,omitempty"`
	Device           *string                 `protobuf:"bytes,11,opt,name=device" json:"device,omitempty"`
	Price            *float64                `protobuf:"fixed64,12,opt,name=price" json:"price,omitempty"`
	SettleType       *uint32                 `protobuf:"varint,13,opt,name=settle_type,json=settleType" json:"settle_type,omitempty"`
	Adfeedopclist    []*AdBidFeedOpcInfo     `protobuf:"bytes,14,rep,name=adfeedopclist" json:"adfeedopclist,omitempty"`
	Adfeednativeopc  *AdBidFeedNativeOpcInfo `protobuf:"bytes,15,opt,name=adfeednativeopc" json:"adfeednativeopc,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *AdBidFeedDetailInfo) Reset()                    { *m = AdBidFeedDetailInfo{} }
func (m *AdBidFeedDetailInfo) String() string            { return proto.CompactTextString(m) }
func (*AdBidFeedDetailInfo) ProtoMessage()               {}
func (*AdBidFeedDetailInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AdBidFeedDetailInfo) GetAdId() uint32 {
	if m != nil && m.AdId != nil {
		return *m.AdId
	}
	return 0
}

func (m *AdBidFeedDetailInfo) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *AdBidFeedDetailInfo) GetFeedId() uint64 {
	if m != nil && m.FeedId != nil {
		return *m.FeedId
	}
	return 0
}

func (m *AdBidFeedDetailInfo) GetCustId() uint64 {
	if m != nil && m.CustId != nil {
		return *m.CustId
	}
	return 0
}

func (m *AdBidFeedDetailInfo) GetFeedPostTime() string {
	if m != nil && m.FeedPostTime != nil {
		return *m.FeedPostTime
	}
	return ""
}

func (m *AdBidFeedDetailInfo) GetPsid() string {
	if m != nil && m.Psid != nil {
		return *m.Psid
	}
	return ""
}

func (m *AdBidFeedDetailInfo) GetAdType() int32 {
	if m != nil && m.AdType != nil {
		return *m.AdType
	}
	return 0
}

func (m *AdBidFeedDetailInfo) GetImpression() uint32 {
	if m != nil && m.Impression != nil {
		return *m.Impression
	}
	return 0
}

func (m *AdBidFeedDetailInfo) GetUpdatetime() string {
	if m != nil && m.Updatetime != nil {
		return *m.Updatetime
	}
	return ""
}

func (m *AdBidFeedDetailInfo) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *AdBidFeedDetailInfo) GetDevice() string {
	if m != nil && m.Device != nil {
		return *m.Device
	}
	return ""
}

func (m *AdBidFeedDetailInfo) GetPrice() float64 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *AdBidFeedDetailInfo) GetSettleType() uint32 {
	if m != nil && m.SettleType != nil {
		return *m.SettleType
	}
	return 0
}

func (m *AdBidFeedDetailInfo) GetAdfeedopclist() []*AdBidFeedOpcInfo {
	if m != nil {
		return m.Adfeedopclist
	}
	return nil
}

func (m *AdBidFeedDetailInfo) GetAdfeednativeopc() *AdBidFeedNativeOpcInfo {
	if m != nil {
		return m.Adfeednativeopc
	}
	return nil
}

func init() {
	proto.RegisterType((*AdBidFeedContentOps)(nil), "websidx_interface.AdBidFeedContentOps")
	proto.RegisterType((*KeyValue)(nil), "websidx_interface.KeyValue")
	proto.RegisterType((*AdBidFeedOpcInfo)(nil), "websidx_interface.AdBidFeedOpcInfo")
	proto.RegisterType((*AdBidFeedNativeOpcInfo)(nil), "websidx_interface.AdBidFeedNativeOpcInfo")
	proto.RegisterType((*AdBidFeedDetailInfo)(nil), "websidx_interface.AdBidFeedDetailInfo")
}

func init() { proto.RegisterFile("bidfeed_msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 597 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x13, 0x27, 0x71, 0xc6, 0x49, 0x3f, 0xb6, 0xa8, 0x58, 0x2d, 0x82, 0x2a, 0x45, 0xa8,
	0x5c, 0x72, 0xc8, 0x85, 0x33, 0x1f, 0x02, 0x45, 0x20, 0x5a, 0x99, 0x8a, 0x6b, 0xb4, 0xf1, 0x6e,
	0x22, 0x0b, 0xc7, 0xb6, 0xbc, 0x9b, 0x94, 0xfc, 0x09, 0xc4, 0x5f, 0xe0, 0x9f, 0x32, 0x33, 0x9b,
	0xb8, 0x69, 0x29, 0xbd, 0xed, 0xbc, 0xd9, 0x37, 0xf3, 0xfc, 0xf6, 0x19, 0x0e, 0xa7, 0xa9, 0x9a,
	0x69, 0xad, 0x26, 0x0b, 0x33, 0x1f, 0x96, 0x55, 0x61, 0x0b, 0x71, 0x78, 0xa3, 0xa7, 0x26, 0x55,
	0x3f, 0x27, 0x69, 0x6e, 0x75, 0x35, 0x93, 0x89, 0x3e, 0xa9, 0xa1, 0xfa, 0xd6, 0xa0, 0x82, 0xa3,
	0xb7, 0xea, 0x5d, 0xaa, 0x3e, 0x22, 0xf9, 0x7d, 0x81, 0x37, 0x73, 0x7b, 0x59, 0x1a, 0x21, 0xc0,
	0xb7, 0xeb, 0x52, 0x47, 0xde, 0x59, 0xe3, 0xa2, 0x1f, 0xf3, 0x59, 0x7c, 0x82, 0x50, 0xba, 0x25,
	0x69, 0x3e, 0x2b, 0xa2, 0x06, 0xb6, 0xc2, 0xd1, 0xab, 0xe1, 0x3f, 0x6b, 0x86, 0xf5, 0xc0, 0x0f,
	0xda, 0xca, 0x34, 0x1b, 0xe3, 0xed, 0x18, 0x1c, 0x95, 0xce, 0x83, 0x11, 0x04, 0x9f, 0xf5, 0xfa,
	0xbb, 0xcc, 0x96, 0x5a, 0x1c, 0x40, 0xf3, 0x87, 0x5e, 0xf3, 0x9e, 0x6e, 0x4c, 0x47, 0xf1, 0x04,
	0x5a, 0x2b, 0x6a, 0xe1, 0x82, 0x26, 0x62, 0xae, 0x18, 0xfc, 0x69, 0xc0, 0x41, 0x3d, 0xf7, 0xb2,
	0x4c, 0x68, 0x10, 0x91, 0xe5, 0x9c, 0x44, 0x36, 0x51, 0x24, 0x1d, 0xc5, 0x31, 0xb4, 0xe7, 0x3a,
	0x57, 0xba, 0x62, 0x76, 0x3f, 0xde, 0x54, 0xe2, 0x04, 0x82, 0xac, 0x48, 0xa4, 0x4d, 0x8b, 0x3c,
	0x6a, 0x72, 0xa7, 0xae, 0xc5, 0x33, 0xe8, 0xb2, 0x76, 0x6d, 0xac, 0x89, 0x7c, 0x6e, 0xde, 0x02,
	0xc4, 0x44, 0x6f, 0x6f, 0x8a, 0x4a, 0x99, 0xa8, 0xc5, 0x8a, 0xea, 0xba, 0x76, 0xa9, 0xcd, 0xea,
	0x9d, 0x4b, 0xa7, 0xd0, 0x4d, 0x96, 0xc6, 0x4e, 0xb2, 0xd4, 0xd8, 0xa8, 0x83, 0x04, 0x3f, 0x0e,
	0x08, 0xf8, 0x82, 0xb5, 0x38, 0x87, 0x7e, 0x55, 0xac, 0x65, 0x66, 0xd7, 0x93, 0xb2, 0x4a, 0x13,
	0x1d, 0x05, 0x67, 0xde, 0x85, 0x17, 0xf7, 0x36, 0xe0, 0x15, 0x61, 0xe2, 0x0d, 0x04, 0xb8, 0x5a,
	0x57, 0x2b, 0xad, 0xa2, 0x2e, 0x0e, 0x08, 0x47, 0xa7, 0x0f, 0x98, 0xbc, 0x75, 0x30, 0xae, 0x2f,
	0x0f, 0x7e, 0x79, 0x70, 0x5c, 0x7b, 0xf4, 0x15, 0x3f, 0x6e, 0xa5, 0xb7, 0x4e, 0xa1, 0x2f, 0x3a,
	0x97, 0xd3, 0x8c, 0xcc, 0xf2, 0xc8, 0x17, 0x57, 0x6d, 0x1d, 0x6c, 0x3c, 0xe4, 0x60, 0xf3, 0xbf,
	0x0e, 0xfa, 0xf7, 0x1c, 0x44, 0x8e, 0xd2, 0x2b, 0xfa, 0x9e, 0x96, 0xe3, 0xb8, 0x6a, 0xf0, 0xdb,
	0xdf, 0x49, 0xd7, 0x6d, 0x18, 0xc4, 0x11, 0xb4, 0x24, 0xa6, 0x48, 0x6d, 0xe3, 0x25, 0xd5, 0x58,
	0xd1, 0x10, 0x63, 0xa5, 0x5d, 0x1a, 0x4e, 0x56, 0x2b, 0xde, 0x54, 0xe2, 0x29, 0x74, 0x5c, 0xe8,
	0x14, 0x2a, 0xf2, 0xd0, 0xce, 0x36, 0x07, 0x49, 0x51, 0x83, 0x9d, 0xc6, 0x86, 0xef, 0x1a, 0x54,
	0x62, 0xe3, 0x25, 0xec, 0x31, 0xa3, 0x2c, 0xb0, 0x6b, 0xd3, 0x05, 0xc9, 0xf2, 0xf0, 0x81, 0x7a,
	0x84, 0x5e, 0x21, 0x78, 0x8d, 0x18, 0x3d, 0x5e, 0x89, 0x9e, 0xe2, 0xe3, 0x51, 0x8f, 0xcf, 0x34,
	0x12, 0x85, 0xf1, 0x9b, 0x76, 0x10, 0x46, 0x11, 0x52, 0x5d, 0xd3, 0xab, 0x3e, 0x07, 0x48, 0x17,
	0x25, 0x3a, 0x6d, 0xe8, 0xfb, 0x03, 0xf6, 0x70, 0x07, 0xa1, 0xfe, 0xb2, 0x54, 0xd2, 0x6a, 0x5e,
	0xd7, 0xe5, 0x91, 0x3b, 0x88, 0x88, 0xa0, 0xb3, 0xd2, 0x15, 0x93, 0x81, 0x07, 0x6f, 0xcb, 0x1d,
	0xef, 0x42, 0x66, 0x6d, 0x2a, 0xfa, 0x0d, 0x5c, 0x44, 0x7a, 0x1c, 0x11, 0x57, 0x88, 0x17, 0x10,
	0x1a, 0x6d, 0x6d, 0xa6, 0x9d, 0xc8, 0xbe, 0x13, 0xe2, 0x20, 0x16, 0x3a, 0x86, 0xbe, 0xfb, 0xd3,
	0x8a, 0x32, 0xe1, 0x08, 0xee, 0x71, 0x82, 0xce, 0x1f, 0xfb, 0x4d, 0x37, 0x21, 0x89, 0xef, 0x32,
	0xc5, 0x37, 0xd8, 0x77, 0x40, 0xce, 0x51, 0x42, 0x38, 0xda, 0xc7, 0x7d, 0xe1, 0xe8, 0xf5, 0x63,
	0xc3, 0xee, 0xe4, 0x2e, 0xbe, 0x3f, 0xe1, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x35, 0x5c,
	0x60, 0xa9, 0x04, 0x00, 0x00,
}
